[package]
name = "cbu"
version = "1.0.0"
authors = ["notonetotalk"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
